name: ci

on:
  push:
    branches-ignore: [main]

permissions:
  contents: read

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?schema=public

    services:
      postgres:
        image: postgres:latest
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - run: yarn install
      - run: yarn lint:check
      - run: yarn prisma db push
      - run: yarn test
      - run: yarn test:e2e
      - run: yarn test:cov && coveralls < coverage/lcov.info
